# Generated by Django 4.2 on 2023-04-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0004_alter_trait_created_at'),
        ('pets', '0002_alter_pet_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='pets_with_trait', to='traits.trait'),
        ),
    ]
