# Generated by Django 4.2 on 2023-04-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='traits',
        ),
    ]
