# Generated by Django 4.2 on 2023-04-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_traits'),
        ('traits', '0004_alter_trait_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='pets',
            field=models.ManyToManyField(related_name='traits_with_pet', to='pets.pet'),
        ),
    ]
